name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Go mod download
        run: go mod download

      - name: Build ampybusctl
        run: go build -o ampybusctl ./cmd/ampybusctl

      - name: Go unit tests (if any)
        run: go test ./...

      - name: Validate golden fixtures
        run: ./ampybusctl validate-fixture --dir golden

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install Python package (editable) with nats extra
        run: pip install -e .[nats]

      - name: Import smoke tests
        run: |
          python - <<'PY'
          import ampybus
          from ampybus.headers import new_headers
          h = new_headers("ampy.bars.v1.BarBatch","ci@host","ci","XNAS.AAPL")
          assert h.schema_hash.startswith("nameonly:sha256:")
          print("python sdk import OK")
          PY
